### ISSUE TITLE
Windows / harfbuzz_ot_demo / '=' expected near 'const'

### ISSUE THREAD

**Issue by Robert-M-Muench** [luapower/harfbuzz#1]
D:\develop\Lua\luapower> ./luajit .\harfbuzz_ot_demo.lua
D:\develop\Lua\luapower\bin\mingw64\luajit.exe: .\harfbuzz_ot_demo.lua:13: '=' expected near 'const'

**Comment by capr** [comment]
removed abandoned harfbuzz_ot_demo
